package compose

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

func sampleLock() Lock {
	return Lock{
		Arch:       "x86_64",
		SourceDate: time.Date(2026, 6, 1, 0, 0, 0, 0, time.UTC),
		Manifest:   "peipkg-manifest-2026-6-1.toml",
		Packages: []LockedPackage{
			{Name: "nginx", Version: "1.27.5-1", Architecture: "x86_64", Source: "official",
				URL: "https://pkgs.peios.org/pool/nginx-1.27.5.peipkg", Hash: strings.Repeat("a", 64)},
			{Name: "base", Version: "3.2.0-1", Architecture: "x86_64", Source: "official",
				URL: "https://pkgs.peios.org/pool/base-3.2.0.peipkg", Hash: strings.Repeat("b", 64)},
		},
	}
}

func TestLockRoundTrip(t *testing.T) {
	data, err := sampleLock().Encode()
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	got, err := DecodeLock(data)
	if err != nil {
		t.Fatalf("DecodeLock: %v", err)
	}

	if got.Arch != "x86_64" || got.Manifest != "peipkg-manifest-2026-6-1.toml" {
		t.Errorf("decoded lock = %+v", got)
	}
	if !got.SourceDate.Equal(sampleLock().SourceDate) {
		t.Errorf("SourceDate = %v", got.SourceDate)
	}
	// Packages are emitted sorted by name, so base precedes nginx.
	if len(got.Packages) != 2 || got.Packages[0].Name != "base" ||
		got.Packages[1].Name != "nginx" {
		t.Fatalf("packages not sorted by name: %+v", got.Packages)
	}
	if got.Packages[1] != sampleLock().Packages[0] {
		t.Errorf("nginx round-tripped as %+v", got.Packages[1])
	}
}

func TestLockEncodeDeterministic(t *testing.T) {
	a, err := sampleLock().Encode()
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	b, err := sampleLock().Encode()
	if err != nil {
		t.Fatalf("Encode: %v", err)
	}
	if !bytes.Equal(a, b) {
		t.Errorf("Encode is not deterministic:\n%s\n---\n%s", a, b)
	}
	if !bytes.HasPrefix(a, []byte("# generated by peipkg-compose")) {
		t.Errorf("encoded lock lacks the do-not-edit header")
	}
}

func TestLockPath(t *testing.T) {
	cases := map[string]string{
		"peipkg-manifest-2026-6-1.toml":     "peipkg-manifest-2026-6-1.lock.toml",
		"build/peimanifest.toml":            "build/peimanifest.lock.toml",
		"manifest":                          "manifest.lock.toml",
	}
	for in, want := range cases {
		if got := LockPath(in); got != want {
			t.Errorf("LockPath(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestDecodeLockErrors(t *testing.T) {
	const hdr = "schema = 1\narch = \"x86_64\"\nsource_date = \"2026-06-01T00:00:00Z\"\n"
	const okPkg = "[[package]]\nname=\"a\"\nversion=\"1.0-1\"\narchitecture=\"x86_64\"\n" +
		"source=\"official\"\nurl=\"https://x/a.peipkg\"\nhash=\"" +
		"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\"\n"
	cases := map[string]struct{ toml, want string }{
		"wrong schema": {"schema = 2\narch=\"x\"\nsource_date=\"2026-06-01T00:00:00Z\"\n" + okPkg,
			`schema is 2, want 1`},
		"no packages":   {hdr, `contains no packages`},
		"missing field": {hdr + "[[package]]\nname=\"a\"\nversion=\"1.0-1\"\n", `missing "architecture"`},
		"bad hash": {hdr + "[[package]]\nname=\"a\"\nversion=\"1.0-1\"\narchitecture=\"x86_64\"\n" +
			"source=\"official\"\nurl=\"https://x/a\"\nhash=\"abc\"\n", `want a 64-hex SHA-256`},
		"duplicate package": {hdr + okPkg + okPkg, `more than once`},
	}
	for name, tc := range cases {
		t.Run(name, func(t *testing.T) {
			_, err := DecodeLock([]byte(tc.toml))
			if err == nil {
				t.Fatalf("DecodeLock accepted invalid input")
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("error %q does not contain %q", err, tc.want)
			}
		})
	}
}
