[package]
name        = "dev.peios.peipkg-compose-debuginfo"
description = "Debugging symbols for the Peios package-root composer"

[dependencies]
"dev.peios.peipkg-compose" = "= {{release}}"

[files]
"@source:LICENSE"                  = "usr/share/licenses/dev.peios.peipkg-compose-debuginfo/LICENSE"
":debug/compose/usr/lib/debug/**" = "usr/lib/debug"
