[package]
name        = "dev.peios.peipkg-debuginfo"
description = "Debugging symbols for the Peios package manager"

[dependencies]
"dev.peios.peipkg" = "= {{release}}"

[files]
"@source:LICENSE"                 = "usr/share/licenses/dev.peios.peipkg-debuginfo/LICENSE"
":debug/peipkg/usr/lib/debug/**" = "usr/lib/debug"
